source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'WCAlertController_Example', :exclusive => true do
  pod 'WCAlertController', :path => '../'
end

target 'WCAlertController_Tests', :exclusive => true do
  pod 'WCAlertController', :path => '../'

  
end
